### ISSUE TITLE
new suggestion

### ISSUE THREAD

**Issue by EdeAbreu23** [clara-j/media_cleaner#22]
Hello @terrelsa13  we probably already talked about this so i really like the latest script but i would like to know if there is a chance for another change. so you know you added the possibility to delete videos depending on the date the movie/show was added to the library. is there a way to do this by path? so lets say i would like to delete movies/tv shows from the library people request to me if it was added more than 30 days ago but my personal movies i would not like to touch or maybe 1 year. but right now it is deleting it for all libraries 

also is there a way to include the name of the user for which something is been deleted?
![image](https://user-images.githubusercontent.com/7027367/117957722-41d20c00-b312-11eb-9d6a-94a2721343f9.png)
on the image above everything is from my username except the movie and i had to go up and check the user through the whole list to see what user already watched that. it would be nice to have the username here in this list of deleting items

Thanks!

**Comment by terrelsa13** [comment]
@elvis0288

1. It sounds like you will need to run two separate instances of this script... Copy and rename the folder the script is currently in. Setup the first instance to only delete from libraries people have requested from you and set it to delete at 30 days. Setup the second instance to only delete from your personal libraries and set it to delete at 365 days. Make sure these libraries do not overlap.

2. This request sounds possible. I thought about adding user names a while back, but decided against it because it felt redundant. Currently user names are not stored with the media items to be deleted when the section you show is printed out. I may implement this when I have enough free time to sit down and look into it further to understand what else would have to change in order to show the user names at the bottom. But as you mentioned, the same information is already shown above. For now, that will have to suffice.

**Comment by EdeAbreu23** [comment]
1. so i do not follow i am talking about this:
![image](https://user-images.githubusercontent.com/7027367/118002788-df900000-b33f-11eb-867c-397e44d9bb9a.png)
is this also using the path i indicated on the blacklist:
![image](https://user-images.githubusercontent.com/7027367/118002884-f7678400-b33f-11eb-94e1-b5e7e41480d2.png)
what i mean is lets say some paths i would like to delete after 1 years other less time but it looks like you just go over everything in my jellyfin without path. am i right?

**Comment by terrelsa13** [comment]
1. The max delete functionality uses the same `user_bl_libs=` and `user_wl_libs=` paths the rest of the script uses. There will be no separate paths for the max delete functionality.

**To do what you asked for in the original post you will need to run this script from two separate folders (two instances). For example:**

- C:\MyComputer\MyFolders\MediaCleaner30Days\media_cleaner\media_cleaner.py
- C:\MyComputer\MyFolders\MediaCleaner365Days\media_cleaner\media_cleaner.py

**Each instance above will have its own media_cleaner_config.py.**

- The 30Days instance will be configured for the "other users" and the "other libraries". It will be set to delete watched media at, let's say, 15 days and max age media at 30 days of age.
- The 365 day instance will be configured for "your personal user" and "your personal libraries". It will be set to delete watched media at, let's say, 45 days and max age media at 365 days of age

This can be expanded to any number of script instances to get very specific media cleaning functionality.

**Comment by EdeAbreu23** [comment]
that makes sense i did not know you were using the same paths for deleting the those medias.. thanks
